//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachingAssignmentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class knowledge_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public knowledge_type()
        {
            this.curricula = new HashSet<curriculum>();
        }
    
        public int id { get; set; }
        public string knowledge_type_alias { get; set; }
        public string group_1 { get; set; }
        public string group_2 { get; set; }
        public string group_3 { get; set; }
        public Nullable<int> compulsory_credits { get; set; }
        public Nullable<int> optional_credits { get; set; }
        public int student_course_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curriculum> curricula { get; set; }
    }
}
